--
-- PostgreSQL database dump
--

\restrict w3JAWCtUTUvzIxAb3nrG2GKeWf8USRaxUt8KicEZfPaUEWz1T1xMMYYQNmUE0OV

-- Dumped from database version 14.23
-- Dumped by pg_dump version 14.23

-- Started on 2026-06-09 06:32:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 16486)
-- Name: authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authors (
    birth_date date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    nationality character varying(50),
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL
);


ALTER TABLE public.authors OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16485)
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16492)
-- Name: books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.books (
    available_copies integer NOT NULL,
    publication_year integer NOT NULL,
    total_copies integer NOT NULL,
    author_id bigint,
    category_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    isbn character varying(13) NOT NULL,
    title character varying(200) NOT NULL
);


ALTER TABLE public.books OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16491)
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16500)
-- Name: borrowings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.borrowings (
    borrow_date date NOT NULL,
    due_date date NOT NULL,
    return_date date,
    book_id bigint,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    user_id bigint,
    status character varying(20)
);


ALTER TABLE public.borrowings OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16499)
-- Name: borrowings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.borrowings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.borrowings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16506)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16505)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16514)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    is_active boolean,
    membership_date date NOT NULL,
    id bigint NOT NULL,
    phone character varying(20),
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16513)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3344 (class 0 OID 16486)
-- Dependencies: 210
-- Data for Name: authors; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authors (birth_date, created_at, id, updated_at, nationality, name, surname) FROM stdin;
1884-06-11	2026-06-07 14:43:54.951478	1	2026-06-07 14:43:54.951478	Türk	Halide Edib	Adıvar
1907-02-25	2026-06-07 14:56:40.768492	3	2026-06-07 14:56:40.768492	Türk	Said	Ali
1907-02-25	2026-06-07 15:00:48.564043	4	2026-06-07 15:00:48.564043	Türk	Bediüzzaman	Nur
1907-02-25	2026-06-07 15:15:51.003434	5	2026-06-07 15:15:51.003434	Türk	Bediüzzaman 2	Nur
1884-06-11	2026-06-07 15:16:38.374144	6	2026-06-07 15:16:38.374144	Kürt	Recaizade Mahmut Ekrem	Araba sevdası
1884-06-11	2026-06-07 15:19:31.17232	7	2026-06-07 15:19:31.17232	Kürt	Recaizade 	Araba sevdası
1884-06-11	2026-06-08 23:09:19.496552	8	2026-06-08 23:09:19.496552	Kürt	hasan  	Araba sevdası
1884-06-11	2026-06-08 23:21:38.68191	9	2026-06-08 23:21:38.68191	Kürt	Mustafa 	Araba sevdası
\.


--
-- TOC entry 3346 (class 0 OID 16492)
-- Dependencies: 212
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.books (available_copies, publication_year, total_copies, author_id, category_id, created_at, id, updated_at, isbn, title) FROM stdin;
2	1943	2	3	1	2026-06-08 05:16:47.578148	3	2026-06-08 05:16:47.578148	9789750800000	Kürk Mantolu Madonna
2	1943	2	3	1	2026-06-08 23:42:02.553701	5	2026-06-08 23:42:02.553701	97897000	Türk Mantolu Madonna
10	2026	10	1	1	2026-06-08 05:12:18.724829	1	2026-06-09 00:06:50.56354	978-000000000	Yeni Başlık 3
2	1943	2	3	1	2026-06-09 01:30:38.731393	10	2026-06-09 01:30:38.731393	978975000	Kürk Mantolu Madonna3
\.


--
-- TOC entry 3348 (class 0 OID 16500)
-- Dependencies: 214
-- Data for Name: borrowings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.borrowings (borrow_date, due_date, return_date, book_id, created_at, id, user_id, status) FROM stdin;
2026-06-08	2026-07-08	2026-06-08	1	2026-06-08 13:26:51.509638	1	1	RETURNED
\.


--
-- TOC entry 3350 (class 0 OID 16506)
-- Dependencies: 216
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name, description) FROM stdin;
1	Roman	\N
3	Risale-i Nur Külliyatı	Dini
4	Recaizade Mahmut Ekrem	\N
5	Recaizade  Ekrem	\N
6	Öykü Hikaye	Modern Dünya
7	Risale-i Nur Külliyatı 2 	Dini
\.


--
-- TOC entry 3352 (class 0 OID 16514)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (is_active, membership_date, id, phone, first_name, last_name, email) FROM stdin;
t	2026-06-09	2	055500000	Emirsah	Erdem	zarafetAksesuar@test.com
t	2026-06-09	7	055500000	Emirsah	Erdem	Aksesuar@test.com
t	2026-06-09	8	055500000	Emirsah	Erdem	zarafet 2@test.com
t	2026-06-08	1	0555000000	Hasan	Erdem	yeni.email@test.com
\.


--
-- TOC entry 3358 (class 0 OID 0)
-- Dependencies: 209
-- Name: authors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.authors_id_seq', 9, true);


--
-- TOC entry 3359 (class 0 OID 0)
-- Dependencies: 211
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.books_id_seq', 10, true);


--
-- TOC entry 3360 (class 0 OID 0)
-- Dependencies: 213
-- Name: borrowings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.borrowings_id_seq', 1, true);


--
-- TOC entry 3361 (class 0 OID 0)
-- Dependencies: 215
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 7, true);


--
-- TOC entry 3362 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- TOC entry 3185 (class 2606 OID 16490)
-- Name: authors authors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);


--
-- TOC entry 3187 (class 2606 OID 16498)
-- Name: books books_isbn_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_isbn_key UNIQUE (isbn);


--
-- TOC entry 3189 (class 2606 OID 16496)
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- TOC entry 3191 (class 2606 OID 16504)
-- Name: borrowings borrowings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowings
    ADD CONSTRAINT borrowings_pkey PRIMARY KEY (id);


--
-- TOC entry 3193 (class 2606 OID 16512)
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- TOC entry 3195 (class 2606 OID 16510)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 16520)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 3199 (class 2606 OID 16518)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3202 (class 2606 OID 16531)
-- Name: borrowings fk6q1qai7on9rcryji44lyglqt1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowings
    ADD CONSTRAINT fk6q1qai7on9rcryji44lyglqt1 FOREIGN KEY (book_id) REFERENCES public.books(id);


--
-- TOC entry 3203 (class 2606 OID 16536)
-- Name: borrowings fkaexiaowfdka601ns4qv7pu0re; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.borrowings
    ADD CONSTRAINT fkaexiaowfdka601ns4qv7pu0re FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3200 (class 2606 OID 16521)
-- Name: books fkfjixh2vym2cvfj3ufxj91jem7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT fkfjixh2vym2cvfj3ufxj91jem7 FOREIGN KEY (author_id) REFERENCES public.authors(id);


--
-- TOC entry 3201 (class 2606 OID 16526)
-- Name: books fkleqa3hhc0uhfvurq6mil47xk0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT fkleqa3hhc0uhfvurq6mil47xk0 FOREIGN KEY (category_id) REFERENCES public.categories(id);


-- Completed on 2026-06-09 06:32:34

--
-- PostgreSQL database dump complete
--

\unrestrict w3JAWCtUTUvzIxAb3nrG2GKeWf8USRaxUt8KicEZfPaUEWz1T1xMMYYQNmUE0OV

